version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ferry_web
    command: /start
    env_file:
      - .env
    environment:
      - SQL_DATABASE=ferry
      - SQL_USER=ferry
      - SQL_PASSWORD=ferry
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ferry
      - POSTGRES_USER=ferry
      - POSTGRES_PASSWORD=ferry

volumes:
  postgres_data:
